# Generated by Django 4.1.3 on 2022-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=100)),
                ("drink", models.BooleanField(default=False)),
                ("calories", models.IntegerField()),
                ("carbs", models.IntegerField()),
                ("liquid", models.IntegerField()),
                ("sodium", models.IntegerField(blank=True)),
                ("caffene", models.IntegerField(blank=True)),
            ],
        ),
    ]
