# Generated by Django 4.1.3 on 2022-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrition",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
