# Generated by Django 4.1.3 on 2022-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_nutrition_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrition",
            name="category",
            field=models.CharField(
                choices=[
                    ("drink", "Drink"),
                    ("food", "Food"),
                    ("caffene", "Caffene"),
                    ("sodium", "Sodium"),
                    ("water", "Water"),
                ],
                default="Food",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
