# Generated by Django 4.1.3 on 2022-11-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_nutrition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrition",
            name="brand_name",
            field=models.CharField(default="None", max_length=100),
        ),
    ]
