# Generated by Django 4.1.3 on 2022-11-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_nutrition_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrition",
            name="category",
            field=models.CharField(
                choices=[
                    ("drink", "Drink"),
                    ("food", "Food"),
                    ("caffene", "Caffene"),
                    ("sodium_drink", "Sodium Drink"),
                    ("sodium_food", "Sodium Tabs and Powders"),
                    ("water", "Water"),
                ],
                max_length=20,
            ),
        ),
    ]
