# Generated by Django 4.1.3 on 2023-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_calculationentry_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationentry",
            name="entry_date",
            field=models.DateTimeField(),
        ),
    ]
