# Generated by Django 4.1.3 on 2023-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_nutrition_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrition",
            name="carry_weight",
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
